import { Message } from "../types/message.js"

export interface BehavioralRule {
  name: string
  check: (output: string, context: Message[]) => { compliant: boolean; reason: string }
}

export class BehavioralComplianceFilter {
  private rules: BehavioralRule[]

  constructor(rules: BehavioralRule[]) {
    this.rules = rules
  }

  /**
   * Runs the compliance check against the proposed output and context.
   * @param output The final text output generated by the agent.
   * @param context The history of messages leading up to the output.
   * @returns An array of compliance results, indicating which rules passed or failed.
   */
  runComplianceCheck(output: string, context: Message[]): { compliant: boolean; violations: { ruleName: string; reason: string }[] } {
    const violations: { ruleName: string; reason: string }[] = []
    let isCompliant = true

    for (const rule of this.rules) {
      const result = rule.check(output, context)
      if (!result.compliant) {
        isCompliant = false
        violations.push({
          ruleName: rule.name,
          reason: result.reason
        })
      }
    }

    return {
      compliant: isCompliant,
      violations: violations
    }
  }
}