import {
    Message,
    UserMessage,
    AssistantMessage,
    ToolResultMessage,
    ContentBlock,
    TextBlock,
    ToolUseBlock,
    ThinkingBlock,
    LoopEvent
} from "./types";

export type SchemaDiff = {
    added: {
        [key: string]: any;
    };
    removed: {
        [key: string]: any;
    };
    modified: {
        [key: string]: {
            old: any;
            new: any;
            changes: {
                type: "type" | "required" | "description";
                message: string;
            }[];
        };
    };
};

export type Schema = {
    type: "object";
    properties: {
        [key: string]: {
            type: "string" | "number" | "boolean" | "array" | "object";
            description?: string;
            required?: boolean;
            items?: Schema;
            properties?: {
                [key: string]: {
                    type: "string" | "number" | "boolean" | "array" | "object";
                    description?: string;
                    required?: boolean;
                    items?: Schema;
                    properties?: {
                        [key: string]: {
                            type: "string" | "number" | "boolean" | "array" | "object";
                            description?: string;
                            required?: boolean;
                            items?: Schema;
                            properties?: {
                                [key: string]: {
                                    type: "string" | "number" | "boolean" | "array" | "object";
                                    description?: string;
                                    required?: boolean;
                                    items?: Schema;
                                    properties?: {
                                        [key: string]: {
                                            type: "string" | "number" | "boolean" | "array" | "object";
                                            description?: string;
                                            required?: boolean;
                                            items?: Schema;
                                            properties?: {
                                                [key: string]: {
                                                    type: "string" | "number" | "boolean" | "array" | "object";
                                                    description?: string;
                                                    required?: boolean;
                                                    items?: Schema;
                                                    properties?: {
                                                        [key: string]: {
                                                            type: "string" | "number" | "boolean" | "array" | "object";
                                                            description?: string;
                                                            required?: boolean;
                                                            items?: Schema;
                                                            properties?: {
                                                                [key: string]: {
                                                                    type: "string" | "number" | "boolean" | "array" | "object";
                                                                    description?: string;
                                                                    required?: boolean;
                                                                    items?: Schema;
                                                                    properties?: {
                                                                        [key: string]: {
                                                                            type: "string" | "number" | "boolean" | "array" | "object";
                                                                            description?: string;
                                                                            required?: boolean;
                                                                            items?: Schema;
                                                                            properties?: {
                                                                                [key: string]: {
                                                                                    type: "string" | "number" | "boolean" | "array" | "object";
                                                                                    description?: string;
                                                                                    required?: boolean;
                                                                                    items?: Schema;
                                                                                    properties?: {
                                                                                        [key: string]: {
                                                                                            type: "string" | "number" | "boolean" | "array" | "object";
                                                                                            description?: string;
                                                                                            required?: boolean;
                                                                                            items?: Schema;
                                                                                            properties?: {
                                                                                                [key: string]: {
                                                                                                    type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                    description?: string;
                                                                                                    required?: boolean;
                                                                                                    items?: Schema;
                                                                                                    properties?: {
                                                                                                        [key: string]: {
                                                                                                            type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                            description?: string;
                                                                                                            required?: boolean;
                                                                                                            items?: Schema;
                                                                                                            properties?: {
                                                                                                                [key: string]: {
                                                                                                                    type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                    description?: string;
                                                                                                                    required?: boolean;
                                                                                                                    items?: Schema;
                                                                                                                    properties?: {
                                                                                                                        [key: string]: {
                                                                                                                            type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                            description?: string;
                                                                                                                            required?: boolean;
                                                                                                                            items?: Schema;
                                                                                                                            properties?: {
                                                                                                                                [key: string]: {
                                                                                                                                    type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                    description?: string;
                                                                                                                                    required?: boolean;
                                                                                                                                    items?: Schema;
                                                                                                                                    properties?: {
                                                                                                                                        [key: string]: {
                                                                                                                                            type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                            description?: string;
                                                                                                                                            required?: boolean;
                                                                                                                                            items?: Schema;
                                                                                                                                            properties?: {
                                                                                                                                                [key: string]: {
                                                                                                                                                    type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                    description?: string;
                                                                                                                                                    required?: boolean;
                                                                                                                                                    items?: Schema;
                                                                                                                                                    properties?: {
                                                                                                                                                        [key: string]: {
                                                                                                                                                            type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                            description?: string;
                                                                                                                                                            required?: boolean;
                                                                                                                                                            items?: Schema;
                                                                                                                                                            properties?: {
                                                                                                                                                                [key: string]: {
                                                                                                                                                                    type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                    description?: string;
                                                                                                                                                                    required?: boolean;
                                                                                                                                                                    items?: Schema;
                                                                                                                                                                    properties?: {
                                                                                                                                                                        [key: string]: {
                                                                                                                                                                            type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                            description?: string;
                                                                                                                                                                            required?: boolean;
                                                                                                                                                                            items?: Schema;
                                                                                                                                                                            properties?: {
                                                                                                                                                                                [key: string]: {
                                                                                                                                                                                    type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                    description?: string;
                                                                                                                                                                                    required?: boolean;
                                                                                                                                                                                    items?: Schema;
                                                                                                                                                                                    properties?: {
                                                                                                                                                                                        [key: string]: {
                                                                                                                                                                                            type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                            description?: string;
                                                                                                                                                                                            required?: boolean;
                                                                                                                                                                                            items?: Schema;
                                                                                                                                                                                            properties?: {
                                                                                                                                                                                                [key: string]: {
                                                                                                                                                                                                    type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                    description?: string;
                                                                                                                                                                                                    required?: boolean;
                                                                                                                                                                                                    items?: Schema;
                                                                                                                                                                                                    properties?: {
                                                                                                                                                                                                        [key: string]: {
                                                                                                                                                                                                            type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                            description?: string;
                                                                                                                                                                                                            required?: boolean;
                                                                                                                                                                                                            items?: Schema;
                                                                                                                                                                                                            properties?: {
                                                                                                                                                                                                                [key: string]: {
                                                                                                                                                                                                                            type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                            description?: string;
                                                                                                                                                                                                                            required?: boolean;
                                                                                                                                                                                                                            items?: Schema;
                                                                                                                                                                                                                            properties?: {
                                                                                                                                                                                                                                [key: string]: {
                                                                                                                                                                                                                                                        type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                        description?: string;
                                                                                                                                                                                                                                                        required?: boolean;
                                                                                                                                                                                                                                                        items?: Schema;
                                                                                                                                                                                                                                                        properties?: {
                                                                                                                                                                                                                                                            [key: string]: {
                                                                                                                                                                                                                                                                type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                description?: string;
                                                                                                                                                                                                                                                                required?: boolean;
                                                                                                                                                                                                                                                                items?: Schema;
                                                                                                                                                                                                                                                                properties?: {
                                                                                                                                                                                                                                                                                       [key: string]: {
                                                                                                                                                                                                                                                                                           type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                           description?: string;
                                                                                                                                                                                                                                                                                           required?: boolean;
                                                                                                                                                                                                                                                                                           items?: Schema;
                                                                                                                                                                                                                                                                                           properties?: {
                                                                                                                                                                                                                                                                                               [key: string]: {
                                                                                                                                                                                                                                                                                                   type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                   description?: string;
                                                                                                                                                                                                                                                                                                   required?: boolean;
                                                                                                                                                                                                                                                                                                   items?: Schema;
                                                                                                                                                                                                                                                                                                   properties?: {
                                                                                                                                                                                                                                                                                                       [key: string]: {
                                                                                                                                                                                                                                                                                                           type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                           description?: string;
                                                                                                                                                                                                                                                                                                           required?: boolean;
                                                                                                                                                                                                                                                                                                           items?: Schema;
                                                                                                                                                                                                                                                                                                           properties?: {
                                                                                                                                                                                                                                                                                                               [key: string]: {
                                                                                                                                                                                                                                                                                                                   type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                   description?: string;
                                                                                                                                                                                                                                                                                                                   required?: boolean;
                                                                                                                                                                                                                                                                                                                   items?: Schema;
                                                                                                                                                                                                                                                                                                                   properties?: {
                                                                                                                                                                                                                                                                                                                       [key: string]: {
                                                                                                                                                                                                                                                                                                                           type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                           description?: string;
                                                                                                                                                                                                                                                                                                                           required?: boolean;
                                                                                                                                                                                                                                                                                                                           items?: Schema;
                                                                                                                                                                                                                                                                                                                           properties?: {
                                                                                                                                                                                                                                                                                                                                                      [key: string]: {
                                                                                                                                                                                                                                                                                                                                                          type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                          description?: string;
                                                                                                                                                                                                                                                                                                                                                          required?: boolean;
                                                                                                                                                                                                                                                                                                                                                          items?: Schema;
                                                                                                                                                                                                                                                                                                                                                          properties?: {
                                                                                                                                                                                                                                                                                                                                                                                     [key: string]: {
                                                                                                                                                                                                                                                                                                                                                                                         type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                                                         description?: string;
                                                                                                                                                                                                                                                                                                                                                                                         required?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                   items?: Schema;
                                                                                                                                                                                                                                                                                                                                                                                                                   properties?: {
                                                                                                                                                                                                                                                                                                                                                                                                                       [key: string]: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                   type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                                                                                                                   description?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                   required?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                   items?: Schema;
                                                                                                                                                                                                                                                                                                                                                                                                                                                   properties?: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  [key: string]: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      description?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      required?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      items?: Schema;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      properties?: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [key: string]: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     description?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     required?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     items?: Schema;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     properties?: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [key: string]: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    items?: Schema;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    properties?: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               [key: string]: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   description?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   required?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             items?: Schema;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             properties?: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [key: string]: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             description?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             required?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             items?: Schema;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            properties?: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [key: string]: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           description?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           required?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           items?: Schema;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           properties?: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [key: string]: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              description?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              required?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              items?: Schema;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              properties?: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [key: string]: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             description?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             required?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       items?: Schema;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       properties?: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [key: string]: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      description?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      required?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      items?: Schema;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      properties?: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     [key: string]: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type: "string" | "number" | "boolean" | "array" | "object";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description?: string;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required?: boolean;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    items?: Schema;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   properties?: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [key: string]: {